services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-hoppscotch}
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
